language: ruby
rvm:
  - 2.1.0
  - 2.0.0

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
    secure: gEHhAIohPQ7hVrhM5ane3ljQuk7IcS7PhkcrosGVb5bZ9GZJ+Jc39Ra3bnhq05rIZRzWux6x3AfmameekZn8oO5Pn/XWA16/1L0Sp4n7EqbhCuNPUEBKanoAPBAM7HJRAr2Fehdd7jd7aZksqgbXbWSx3FH3oEAki4q1FtMKBQ4=
